name: Build, Push & Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      IMAGE_TAG: nginx
    steps:
      - name: Get code
        uses: actions/checkout@v3
    
      # login to Dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: "build and push"
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY }}:${{ env.IMAGE_TAG }}

  deploy:
    needs: [ "build" ]
    runs-on: ubuntu-22.04
    steps:
      - name: Deploying to EC2 
        uses: appleboy/ssh-action@v0.1.6
        env:
          IMAGE_TAG: nginx
        with:
          host: "13.127.181.125"
          username: ec2-user
          key: ${{ secrets.CICD_PRIVATE_KEY }}
          port: "22"
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY }}:${{ env.IMAGE_TAG }}
            docker kill agency-home || echo "Deploying ..."
            docker run --rm -d -p 7000:80 --name agency-home ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY }}:${{ env.IMAGE_TAG }}
